#! /bin/sh

pkill sxhkd
sxhkd &
picom -b &
pkill polybar
polybar example &
feh --bg-scale /home/caloway/Downloads/Fondos/wallpapersden.com_cool-red-mountains-4k_1920x1080.jpg &


bspc monitor -d 󰋜               

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc config top_padding 0
#bspc config bottom_padding 0
#bspc config left_padding 0
#bspc config right_padding 0
